#################################################
# Begin Makefile template
#################################################

install: $(OUTPUT)
	-@sudo cp -v $(OUTPUT) $(INSTALL_PREFIX)/lib/$(OUTPUT)
	-@sudo cp -v res/DefaultLibunr.ini $(INSTALL_PREFIX)/share/DefaultLibunr.ini

