#################################################
# Begin Makefile template
#################################################

install: $(OUTPUT)
	-@mkdir $(INSTALL_PREFIX)/share/libunr
	-@mkdir $(INSTALL_PREFIX)/include/libunr
	@cp -v $< $(INSTALL_PREFIX)/lib/$<
	@cp -v res/DefaultLibunr.ini $(INSTALL_PREFIX)/share/libunr/DefaultLibunr.ini
	@cp -rv include/* $(INSTALL_PREFIX)/include/libunr/

