find_package(PkgConfig)
pkg_check_modules(PC_VORBISFILE QUIET vorbisfile)
set(VORBISFILE_DEFINITIONS ${PC_VORBISFILE_CFLAGS_OTHER})

find_path(LIBVORBISFILE_INCLUDE_DIR vorbis/vorbisfile.h
          HINTS ${PC_VORBISFILE_INCLUDEDIR} ${PC_VORBISFILE_INCLUDE_DIRS})

find_library(LIBVORBISFILE_LIBRARY NAMES vorbisfile libvorbisfile
             HINTS ${PC_VORBISFILE_LIBDIR} ${PC_VORBISFILE_LIBRARY_DIRS})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Vorbisfile DEFAULT_MSG
		LIBVORBISFILE_LIBRARY LIBVORBISFILE_INCLUDE_DIR)

mark_as_advanced(LIBVORBISFILE_LIBRARY LIBVORBISFILE_INCLUDE_DIR)

set(LIBVORBISFILE_LIBRARIES ${LIBVORBISFILE_LIBRARY})
set(LIBVORBISFILE_INCLUDE_DIRS ${LIBVORBISFILE_INCLUDE_DIR})
